global using RealEstateAd_CleanArchitecture.Domain.Common;
global using RealEstateAd_CleanArchitecture.Domain.Entities;
global using RealEstateAd_CleanArchitecture.Domain.Enums;
global using RealEstateAd_CleanArchitecture.Domain.Events;
global using RealEstateAd_CleanArchitecture.Domain.Exceptions;
global using RealEstateAd_CleanArchitecture.Domain.ValueObjects;